server:
  port:  8080 # 网关端口
spring:
  application:
    name: gateway-service # 服务名称
  cloud:
    gateway:
      routes: # 网关路由配置
        - id: MarketplaceSystem-User  # 路由id，自定义，只要唯一即可
          uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/v1/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: MarketplaceSystem-Order  # 路由id，自定义，只要唯一即可
          uri: http://127.0.0.1:8082 # 路由的目标地址 http就是固定地址
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/v1/orders/** # 这个是按照路径匹配，只要以/user/开头就符合要求
logging:
  level:
    org.springframework.cloud.gateway: DEBUG